/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTaskRequest } from '../../models/create-task-request';

export interface ApiProjectsProjectIdColumnsColumnIdTasksPost$Params {
  projectId: string;
  columnId: string;
      body: CreateTaskRequest
}

export function apiProjectsProjectIdColumnsColumnIdTasksPost(http: HttpClient, rootUrl: string, params: ApiProjectsProjectIdColumnsColumnIdTasksPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiProjectsProjectIdColumnsColumnIdTasksPost.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.path('columnId', params.columnId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiProjectsProjectIdColumnsColumnIdTasksPost.PATH = '/api/projects/{projectId}/columns/{columnId}/tasks';
