/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Column } from '../../models/column';
import { CreateColumnDto } from '../../models/create-column-dto';

export interface ApiProjectsProjectIdColumnsPost$Json$Params {

/**
 * 專案 ID
 */
  projectId: string;
  
    /**
     * 欄位資料
     */
    body?: CreateColumnDto
}

export function apiProjectsProjectIdColumnsPost$Json(http: HttpClient, rootUrl: string, params: ApiProjectsProjectIdColumnsPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Column>> {
  const rb = new RequestBuilder(rootUrl, apiProjectsProjectIdColumnsPost$Json.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Column>;
    })
  );
}

apiProjectsProjectIdColumnsPost$Json.PATH = '/api/projects/{projectId}/columns';
