/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColumnReorderRequestDto } from '../../models/column-reorder-request-dto';

export interface ApiProjectsProjectIdColumnsReorderPatch$Params {

/**
 * 專案 ID
 */
  projectId: string;
  
    /**
     * 欄位排序資料
     */
    body?: ColumnReorderRequestDto
}

export function apiProjectsProjectIdColumnsReorderPatch(http: HttpClient, rootUrl: string, params: ApiProjectsProjectIdColumnsReorderPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiProjectsProjectIdColumnsReorderPatch.PATH, 'patch');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiProjectsProjectIdColumnsReorderPatch.PATH = '/api/projects/{projectId}/columns/reorder';
