/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Column } from '../../models/column';

export interface ApiColumnsProjectProjectIdGet$Plain$Params {

/**
 * 專案 ID
 */
  projectId: string;
}

export function apiColumnsProjectProjectIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiColumnsProjectProjectIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Column>>> {
  const rb = new RequestBuilder(rootUrl, apiColumnsProjectProjectIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Column>>;
    })
  );
}

apiColumnsProjectProjectIdGet$Plain.PATH = '/api/columns/project/{projectId}';
