/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Column } from '../../models/column';

export interface ApiColumnsIdGet$Json$Params {

/**
 * 欄位 ID
 */
  id: string;
}

export function apiColumnsIdGet$Json(http: HttpClient, rootUrl: string, params: ApiColumnsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Column>> {
  const rb = new RequestBuilder(rootUrl, apiColumnsIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Column>;
    })
  );
}

apiColumnsIdGet$Json.PATH = '/api/columns/{id}';
