/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiColumnsColumnIdTasksReorderPatch } from '../fn/task/api-columns-column-id-tasks-reorder-patch';
import { ApiColumnsColumnIdTasksReorderPatch$Params } from '../fn/task/api-columns-column-id-tasks-reorder-patch';
import { apiProjectsProjectIdColumnsColumnIdTasksPost$Json } from '../fn/task/api-projects-project-id-columns-column-id-tasks-post-json';
import { ApiProjectsProjectIdColumnsColumnIdTasksPost$Json$Params } from '../fn/task/api-projects-project-id-columns-column-id-tasks-post-json';
import { apiProjectsProjectIdColumnsColumnIdTasksPost$Plain } from '../fn/task/api-projects-project-id-columns-column-id-tasks-post-plain';
import { ApiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Params } from '../fn/task/api-projects-project-id-columns-column-id-tasks-post-plain';
import { apiTasksColumnColumnIdGet$Json } from '../fn/task/api-tasks-column-column-id-get-json';
import { ApiTasksColumnColumnIdGet$Json$Params } from '../fn/task/api-tasks-column-column-id-get-json';
import { apiTasksColumnColumnIdGet$Plain } from '../fn/task/api-tasks-column-column-id-get-plain';
import { ApiTasksColumnColumnIdGet$Plain$Params } from '../fn/task/api-tasks-column-column-id-get-plain';
import { apiTasksIdDelete } from '../fn/task/api-tasks-id-delete';
import { ApiTasksIdDelete$Params } from '../fn/task/api-tasks-id-delete';
import { apiTasksIdGet$Json } from '../fn/task/api-tasks-id-get-json';
import { ApiTasksIdGet$Json$Params } from '../fn/task/api-tasks-id-get-json';
import { apiTasksIdGet$Plain } from '../fn/task/api-tasks-id-get-plain';
import { ApiTasksIdGet$Plain$Params } from '../fn/task/api-tasks-id-get-plain';
import { apiTasksIdMovePatch } from '../fn/task/api-tasks-id-move-patch';
import { ApiTasksIdMovePatch$Params } from '../fn/task/api-tasks-id-move-patch';
import { apiTasksIdPut } from '../fn/task/api-tasks-id-put';
import { ApiTasksIdPut$Params } from '../fn/task/api-tasks-id-put';
import { KanbanTask } from '../models/kanban-task';

@Injectable({ providedIn: 'root' })
export class TaskService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTasksColumnColumnIdGet()` */
  static readonly ApiTasksColumnColumnIdGetPath = '/api/tasks/column/{columnId}';

  /**
   * 獲取指定欄位的所有任務.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTasksColumnColumnIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksColumnColumnIdGet$Plain$Response(params: ApiTasksColumnColumnIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<KanbanTask>>> {
    return apiTasksColumnColumnIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * 獲取指定欄位的所有任務.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTasksColumnColumnIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksColumnColumnIdGet$Plain(params: ApiTasksColumnColumnIdGet$Plain$Params, context?: HttpContext): Observable<Array<KanbanTask>> {
    return this.apiTasksColumnColumnIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<KanbanTask>>): Array<KanbanTask> => r.body)
    );
  }

  /**
   * 獲取指定欄位的所有任務.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTasksColumnColumnIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksColumnColumnIdGet$Json$Response(params: ApiTasksColumnColumnIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<KanbanTask>>> {
    return apiTasksColumnColumnIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * 獲取指定欄位的所有任務.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTasksColumnColumnIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksColumnColumnIdGet$Json(params: ApiTasksColumnColumnIdGet$Json$Params, context?: HttpContext): Observable<Array<KanbanTask>> {
    return this.apiTasksColumnColumnIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<KanbanTask>>): Array<KanbanTask> => r.body)
    );
  }

  /** Path part for operation `apiTasksIdGet()` */
  static readonly ApiTasksIdGetPath = '/api/tasks/{id}';

  /**
   * 獲取指定任務的詳細資訊.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTasksIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksIdGet$Plain$Response(params: ApiTasksIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<KanbanTask>> {
    return apiTasksIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * 獲取指定任務的詳細資訊.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTasksIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksIdGet$Plain(params: ApiTasksIdGet$Plain$Params, context?: HttpContext): Observable<KanbanTask> {
    return this.apiTasksIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<KanbanTask>): KanbanTask => r.body)
    );
  }

  /**
   * 獲取指定任務的詳細資訊.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTasksIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksIdGet$Json$Response(params: ApiTasksIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<KanbanTask>> {
    return apiTasksIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * 獲取指定任務的詳細資訊.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTasksIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksIdGet$Json(params: ApiTasksIdGet$Json$Params, context?: HttpContext): Observable<KanbanTask> {
    return this.apiTasksIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<KanbanTask>): KanbanTask => r.body)
    );
  }

  /** Path part for operation `apiTasksIdPut()` */
  static readonly ApiTasksIdPutPath = '/api/tasks/{id}';

  /**
   * 更新任務資訊.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTasksIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTasksIdPut$Response(params: ApiTasksIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiTasksIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * 更新任務資訊.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTasksIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTasksIdPut(params: ApiTasksIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiTasksIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiTasksIdDelete()` */
  static readonly ApiTasksIdDeletePath = '/api/tasks/{id}';

  /**
   * 刪除任務.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTasksIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksIdDelete$Response(params: ApiTasksIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiTasksIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * 刪除任務.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTasksIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTasksIdDelete(params: ApiTasksIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiTasksIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiProjectsProjectIdColumnsColumnIdTasksPost()` */
  static readonly ApiProjectsProjectIdColumnsColumnIdTasksPostPath = '/api/projects/{projectId}/columns/{columnId}/tasks';

  /**
   * 在欄位中建立新任務.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectsProjectIdColumnsColumnIdTasksPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Response(params: ApiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<KanbanTask>> {
    return apiProjectsProjectIdColumnsColumnIdTasksPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * 在欄位中建立新任務.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectsProjectIdColumnsColumnIdTasksPost$Plain(params: ApiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Params, context?: HttpContext): Observable<KanbanTask> {
    return this.apiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<KanbanTask>): KanbanTask => r.body)
    );
  }

  /**
   * 在欄位中建立新任務.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectsProjectIdColumnsColumnIdTasksPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectsProjectIdColumnsColumnIdTasksPost$Json$Response(params: ApiProjectsProjectIdColumnsColumnIdTasksPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<KanbanTask>> {
    return apiProjectsProjectIdColumnsColumnIdTasksPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * 在欄位中建立新任務.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectsProjectIdColumnsColumnIdTasksPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectsProjectIdColumnsColumnIdTasksPost$Json(params: ApiProjectsProjectIdColumnsColumnIdTasksPost$Json$Params, context?: HttpContext): Observable<KanbanTask> {
    return this.apiProjectsProjectIdColumnsColumnIdTasksPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<KanbanTask>): KanbanTask => r.body)
    );
  }

  /** Path part for operation `apiTasksIdMovePatch()` */
  static readonly ApiTasksIdMovePatchPath = '/api/tasks/{id}/move';

  /**
   * 移動任務到其他欄位.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTasksIdMovePatch()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTasksIdMovePatch$Response(params: ApiTasksIdMovePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiTasksIdMovePatch(this.http, this.rootUrl, params, context);
  }

  /**
   * 移動任務到其他欄位.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTasksIdMovePatch$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTasksIdMovePatch(params: ApiTasksIdMovePatch$Params, context?: HttpContext): Observable<void> {
    return this.apiTasksIdMovePatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiColumnsColumnIdTasksReorderPatch()` */
  static readonly ApiColumnsColumnIdTasksReorderPatchPath = '/api/columns/{columnId}/tasks/reorder';

  /**
   * 重新排序欄位內的任務.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiColumnsColumnIdTasksReorderPatch()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiColumnsColumnIdTasksReorderPatch$Response(params: ApiColumnsColumnIdTasksReorderPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiColumnsColumnIdTasksReorderPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * 重新排序欄位內的任務.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiColumnsColumnIdTasksReorderPatch$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiColumnsColumnIdTasksReorderPatch(params: ApiColumnsColumnIdTasksReorderPatch$Params, context?: HttpContext): Observable<void> {
    return this.apiColumnsColumnIdTasksReorderPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
