/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KanbanTask } from '../../models/kanban-task';

export interface ApiTasksColumnColumnIdGet$Json$Params {

/**
 * 欄位 ID
 */
  columnId: string;
}

export function apiTasksColumnColumnIdGet$Json(http: HttpClient, rootUrl: string, params: ApiTasksColumnColumnIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<KanbanTask>>> {
  const rb = new RequestBuilder(rootUrl, apiTasksColumnColumnIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('columnId', params.columnId, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<KanbanTask>>;
    })
  );
}

apiTasksColumnColumnIdGet$Json.PATH = '/api/tasks/column/{columnId}';
