/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KanbanTask } from '../../models/kanban-task';

export interface ApiTasksIdGet$Json$Params {

/**
 * 任務 ID
 */
  id: string;
}

export function apiTasksIdGet$Json(http: HttpClient, rootUrl: string, params: ApiTasksIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<KanbanTask>> {
  const rb = new RequestBuilder(rootUrl, apiTasksIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<KanbanTask>;
    })
  );
}

apiTasksIdGet$Json.PATH = '/api/tasks/{id}';
