/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTaskDto } from '../../models/create-task-dto';
import { KanbanTask } from '../../models/kanban-task';

export interface ApiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Params {

/**
 * 專案 ID
 */
  projectId: string;

/**
 * 欄位 ID
 */
  columnId: string;
  
    /**
     * 任務資料
     */
    body?: CreateTaskDto
}

export function apiProjectsProjectIdColumnsColumnIdTasksPost$Plain(http: HttpClient, rootUrl: string, params: ApiProjectsProjectIdColumnsColumnIdTasksPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<KanbanTask>> {
  const rb = new RequestBuilder(rootUrl, apiProjectsProjectIdColumnsColumnIdTasksPost$Plain.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.path('columnId', params.columnId, {"style":"simple"});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<KanbanTask>;
    })
  );
}

apiProjectsProjectIdColumnsColumnIdTasksPost$Plain.PATH = '/api/projects/{projectId}/columns/{columnId}/tasks';
