/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskMoveDto } from '../../models/task-move-dto';

export interface ApiTasksIdMovePatch$Params {

/**
 * 任務 ID
 */
  id: string;
  
    /**
     * 任務移動資料
     */
    body?: TaskMoveDto
}

export function apiTasksIdMovePatch(http: HttpClient, rootUrl: string, params: ApiTasksIdMovePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiTasksIdMovePatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {"style":"simple"});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiTasksIdMovePatch.PATH = '/api/tasks/{id}/move';
