/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskReorderDto } from '../../models/task-reorder-dto';

export interface ApiColumnsColumnIdTasksReorderPatch$Params {

/**
 * 欄位 ID
 */
  columnId: string;
  
    /**
     * 任務排序資料
     */
    body?: TaskReorderDto
}

export function apiColumnsColumnIdTasksReorderPatch(http: HttpClient, rootUrl: string, params: ApiColumnsColumnIdTasksReorderPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiColumnsColumnIdTasksReorderPatch.PATH, 'patch');
  if (params) {
    rb.path('columnId', params.columnId, {"style":"simple"});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiColumnsColumnIdTasksReorderPatch.PATH = '/api/columns/{columnId}/tasks/reorder';
