/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiProjectsProjectIdColumnsReorderPatch$Params {
  projectId: string;
      body: {

/**
 * 重新排序後的欄位 ID 陣列
 */
'columnIds'?: Array<string>;
}
}

export function apiProjectsProjectIdColumnsReorderPatch(http: HttpClient, rootUrl: string, params: ApiProjectsProjectIdColumnsReorderPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiProjectsProjectIdColumnsReorderPatch.PATH, 'patch');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiProjectsProjectIdColumnsReorderPatch.PATH = '/api/projects/{projectId}/columns/reorder';
