/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KanbanTask } from '../models/kanban-task';
export interface Column {
  color: string;
  id?: string | null;
  order?: number;
  projectId?: string | null;
  tasks?: Array<KanbanTask> | null;
  title: string;
}
