/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 欄位重新排序的資料傳輸物件
 */
export interface ColumnReorderRequestDto {

  /**
   * 重新排序後的欄位 ID 陣列
   */
  columnIds: Array<string>;
}
