/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTaskRequest {
  assignee: string;
  description: string;
  dueDate: string;
  priority: 'low' | 'medium' | 'high';
  tags?: Array<string>;
  title: string;
}
