/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 建立專案的資料傳輸物件
 */
export interface CreateProjectDto {

  /**
   * 專案描述
   */
  description?: string | null;

  /**
   * 專案名稱
   */
  name: string;
}
