/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 建立欄位的資料傳輸物件
 */
export interface CreateColumnDto {

  /**
   * 欄位顏色
   */
  color: string;

  /**
   * 欄位標題
   */
  title: string;
}
