/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Column } from '../models/column';
export interface KanbanTask {
  assignee?: string | null;
  column?: Column;
  columnId?: string | null;
  createdAt?: string;
  description?: string | null;
  dueDate?: string | null;
  id?: string | null;
  order?: number;
  priority: string;
  tags?: Array<string> | null;
  title: string;
}
