/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Column } from '../models/column';
export interface Project {
  columns?: Array<Column> | null;
  createdAt?: string;
  description?: string | null;
  id?: string | null;
  name: string;
}
