/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Column } from '../models/column';
export interface Project {

  /**
   * 專案欄位列表
   */
  columns?: Array<Column>;

  /**
   * 建立時間
   */
  createdAt?: string;

  /**
   * 專案描述
   */
  description: string;

  /**
   * 專案唯一識別碼
   */
  id?: string;

  /**
   * 專案名稱
   */
  name: string;
}
