/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 任務移動的資料傳輸物件
 */
export interface TaskMoveDto {

  /**
   * 目標欄位 ID
   */
  columnId: string;

  /**
   * 在目標欄位中的新位置（可選）
   */
  newIndex?: number | null;
}
