/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Task {

  /**
   * 負責人
   */
  assignee: string;

  /**
   * 任務描述
   */
  description: string;

  /**
   * 截止日期
   */
  dueDate: string;

  /**
   * 任務唯一識別碼
   */
  id?: string;

  /**
   * 優先順序
   */
  priority: 'low' | 'medium' | 'high';

  /**
   * 標籤列表
   */
  tags?: Array<string>;

  /**
   * 任務標題
   */
  title: string;
}
