/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 任務重新排序的資料傳輸物件
 */
export interface TaskReorderDto {

  /**
   * 重新排序後的任務 ID 陣列
   */
  taskIds: Array<string>;
}
