/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 更新任務的資料傳輸物件
 */
export interface UpdateTaskDto {

  /**
   * 指派人
   */
  assignee?: string | null;

  /**
   * 任務描述
   */
  description?: string | null;

  /**
   * 截止日期
   */
  dueDate?: string | null;

  /**
   * 優先級
   */
  priority?: string | null;

  /**
   * 標籤列表
   */
  tags?: Array<string> | null;

  /**
   * 任務標題
   */
  title: string;
}
